#!/usr/bin/env python3
import os, re
from pathlib import Path

# --- config ---
IGNORE_DIRS = {
    ".git", ".github", "scripts", "build", "cmake-build-debug", "cmake-build-release",
    "vendor", "third_party", "assets", "docs", "test", "tests", "examples"
}
COUNT_EXT = {".cpp"}
BAR_WIDTH = 340
BAR_HEIGHT = 16
SORT_BY = os.environ.get("TOPIC_SORT", "count")
# -------------

# LeetCode profile + medal (live)
LEETCODE_USERNAME = "AnuragD2192"
LEETCODE_URL = f"https://leetcode.com/u/{LEETCODE_USERNAME}/"
LEETCODE_MEDAL_PAGE_URL = "https://leetcode.com/medal/?showImg=0&id=7459557&isLevel=false"
LEETCODE_MEDAL_IMG_URL  = LEETCODE_MEDAL_PAGE_URL.replace("showImg=0", "showImg=1")  # image version for GitHub

README_TEMPLATE = """\
# Data Structure & Algorithms in C++

[![LeetCode Profile](https://img.shields.io/badge/LeetCode-{leetcode_username}-orange?logo=leetcode&logoColor=white)]({leetcode_url})

A curated collection of C++ questions & solutions for classic Data Structure and Algorithm problems.  
Organized by topic for easy navigation and learning.
Resources: LeetCode, GeeksForGeeks and HackerRank etc.
- 📚 **Topics:** Arrays, Strings, Linked Lists, Trees, Graphs, Heaps, Maps, Tries, and more!
- 📝 **Each folder** contains well-commented `.cpp` solutions.
- 🚀 **Auto-generated progress table** below.

<!-- PROBLEMS_PER_TOPIC:START -->
<!-- auto-generated: do not edit manually -->

{problems_table}

<!-- PROBLEMS_PER_TOPIC:END -->

## My LeetCode
[![LeetCode Stats](https://leetcard.jacoblin.cool/{leetcode_username}?ext=heatmap)]({leetcode_url})

### Live Medal
[<img src="{leetcode_medal_img_url}" alt="LeetCode Medal" height="90" />]({leetcode_medal_page_url})

### License
[![License: MIT](https://img.shields.io/badge/License-MIT-green.svg)](LICENSE)
## How to Use

- Browse by topic folder.
- Each `.cpp` file is a standalone solution.
- Suggestions are welcome!
- Happy Learning

## Contact
- Anurag Dogra
- dogrraanurag@gmail.com

## Auto-update

This README is partially auto-generated by [`scripts/updateReadMe.py`](scripts/updateReadMe.py).
"""

def repo_root() -> Path:
    here = Path(__file__).resolve()
    return here.parents[1] if here.parent.name == "scripts" else here.parent

def count_files(folder: Path) -> int:
    return sum(1 for p in folder.rglob("*") if p.is_file() and p.suffix in COUNT_EXT)

def discover_topics(root: Path):
    topics = []
    for p in root.iterdir():
        if not p.is_dir():
            continue
        name = p.name
        if name.startswith(".") or name.startswith("_") or name in IGNORE_DIRS:
            continue
        topics.append(p)
    return topics

# ----- new: save bars as SVG files so GitHub renders them -----

def slugify(name: str) -> str:
    s = name.strip().replace(" ", "_")
    s = re.sub(r"[^A-Za-z0-9_\-]", "-", s)
    return s[:80]

def ensure_dir(d: Path):
    d.mkdir(parents=True, exist_ok=True)

def write_bar_svg(pct: float, label: str, out_path: Path):
    pct = max(0.0, min(100.0, pct))
    filled = int(BAR_WIDTH * pct / 100.0)
    svg = f"""<svg width="{BAR_WIDTH}" height="{BAR_HEIGHT}" viewBox="0 0 {BAR_WIDTH} {BAR_HEIGHT}" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="{label}">
  <title>{label}</title>
  <rect x="0" y="0" width="{BAR_WIDTH}" height="{BAR_HEIGHT}" rx="4" ry="4" fill="#e5e7eb"/>
  <rect x="0" y="0" width="{filled}" height="{BAR_HEIGHT}" rx="4" ry="4" fill="#22c55e"/>
</svg>
"""
    out_path.write_text(svg, encoding="utf-8")

def build_table(rows, assets_dir: Path):
    ensure_dir(assets_dir)
    total = sum(c for _, c in rows)
    max_count = max((c for _, c in rows), default=1)  # safe if rows empty

    md = []
    md.append("## Problems per Topic\n")
    md.append(f"**Total solved:** {total}\n\n")
    md.append("| Topic | Problems | Progress |\n|---|---:|:--|\n")

    for topic, count in rows:
        pct = 100.0 * count / max_count if max_count else 0.0
        label = f"{topic}: {count} problems ({pct:.0f}%)"
        fname = f"{slugify(topic)}.svg"
        out_path = assets_dir / fname
        write_bar_svg(pct, label, out_path)
        img_md = f"![{label}](assets/bars/{fname})"
        md.append(f"| `{topic}` | **{count}** | {img_md} |\n")

    return "".join(md)

# -------------------------------------------------------------

def write_full_readme(section_md: str, readme: Path):
    content = README_TEMPLATE.format(
        problems_table=section_md,
        leetcode_username=LEETCODE_USERNAME,
        leetcode_url=LEETCODE_URL,
        leetcode_medal_img_url=LEETCODE_MEDAL_IMG_URL,
        leetcode_medal_page_url=LEETCODE_MEDAL_PAGE_URL,
    )
    readme.write_text(content, encoding="utf-8")

def main():
    root = repo_root()
    readme = root / "README.md"
    bars_dir = root / "assets" / "bars"

    topics = discover_topics(root)
    rows = [(t.name, count_files(t)) for t in topics]
    rows = [(name, cnt) for name, cnt in rows if cnt > 0]

    if SORT_BY == "alpha":
        rows.sort(key=lambda x: x[0].lower())
    else:
        rows.sort(key=lambda x: (-x[1], x[0].lower()))

    section_md = build_table(rows, bars_dir)
    write_full_readme(section_md, readme)
    print("README created ✅ (with visible SVG bars)")

if __name__ == "__main__":
    main()
